name: 'Tests'

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - run: go test ./... -race -covermode=atomic -v -count=1
